# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 821ab766d3b0fea97f4b0e7df53635257c38043f635c1b5a27363c82ddebb84aad7dfa4cd5543a4a63052a031784b2200812556f985da9a41d50ddf28590e9f3

test:
  secret_key_base: 2e08ea8b23689286abc27c189607b496fb49e8f722a865f2d668191301387422d70509ed0ba91d86bab0882ed7ae288996a3c2fd6b642690a82e027ab40339fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
